data:
    file: 'tiki.ply'
    method: 'convex'
    divide: 1
train:
    epoch_size: 32
    lr: 0.05
model:
    name: 'pn'
    scale: 0.01
loss:
    face: 0.
    edge: 0.
    point: 0.
    length: 5.
    sample: 1.