data:
    file: 'bowl_pcd.ply'
    method: 'alpha'
    divide: 2
    kargs:
        alpha: 0.3
train:
    epoch_size: 128
    lr: 0.05
model:
    hidden_dim1: 256
    hidden_dim2: 64
    scale: 0.005
