data:
    file: 'bowl_pcd.ply'
    method: 'alpha'
    divide: 0
    kargs:
        alpha: 0.3
train:
    epoch_size: 128
    lr: 0.05
model:
    use_pointnet: true
    init_dim: 64
    hidden_dim1: 256
    hidden_dim2: 64
    scale: 0.001
